eco_acts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.BlogPostList.as_view(), name='blog'),
    path('blog/create/', views.BlogPostCreate.as_view(), name='blogpost_create'),
    path('blog/<int:blogpost_id>/', views.blogpost_detail, name='blogpost_detail'),
    path('accounts/<int:user_id>/', views.user_activities, name='user_activities'),
    path('activities/', views.activities_index, name='index'),
    path('activities/<int:activity_id>/', views.activities_detail, name='detail'),
    path('accounts/<int:user_id>/add_note', views.add_note, name='add_note'),
    path('accounts/<int:pk>/delete_note', views.NoteDelete.as_view(), name='delete_note'),
    path('accounts/<int:pk>/update_note', views.NoteUpdate.as_view(), name='note_update'),
    path('activities/<int:activity_id>/assoc_activity/<int:user_id>/', views.assoc_activity, name='assoc_activity'),
    path('activities/<int:activity_id>/unassoc_activity/<int:user_id>/', views.unassoc_activity, name='unassoc_activity'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date


class Activity(models.Model):
    name = models.CharField(max_length=250)
    savings = models.IntegerField()
    about = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'activity_id': self.id})

class MyActivity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    my_activities = models.ManyToManyField(Activity)

class Note(models.Model):
    name = models.CharField(max_length=100)
    content = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('user_activities', kwargs={'user_id': self.id})

class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    post_date = date.today()
    post = models.CharField(max_length=1000)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogpost_detail', kwargs={'blogpost_id': self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Note

class NoteForm(ModelForm):
  class Meta:
    model = Note
    fields = ['name', 'content']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Activity, MyActivity, User, Note, BlogPost
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import NoteForm


# Create your views here.
def home(request):
  return render(request, 'home.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      MyActivity(user_id = user.id).save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def user_activities(request, user_id):
  user = User.objects.get(id=user_id)
  my_activities = MyActivity.objects.get(user_id=user_id).my_activities.all()
  context = {
    'user': user,
    'my_activities': my_activities,
  }
  note_form = NoteForm()
  return render(request, 'user_activities.html',{ 'note_form': note_form, 'user': user,'my_activities': my_activities,})

@login_required
def assoc_activity(request, activity_id, user_id):
    activity = Activity.objects.get(id=activity_id)
    MyActivity.objects.get(user_id=user_id).my_activities.add(activity)
    return redirect('user_activities', user_id)

@login_required
def unassoc_activity(request, activity_id, user_id):
    activity = Activity.objects.get(id=activity_id)
    MyActivity.objects.get(user_id=user_id).my_activities.remove(activity)
    return redirect('user_activities', user_id)

@login_required
def activities_index(request):
    activities = Activity.objects.all()
    if request.user.username:
        user_activities = MyActivity.objects.get(user_id=request.user.id).my_activities.all()
    else:
        user_activities = {}
    context = {
        'activities': activities,
        'user_activities': user_activities,
    }
    return render(request, 'main_app/activity_list.html', context)

@login_required
def activities_detail(request, activity_id):
    activity = Activity.objects.get(id=activity_id)
    if request.user.username:
        user_activities = MyActivity.objects.get(user_id=request.user.id).my_activities.all()
    else:
        user_activities = {}
    context = {
        'activity': activity,
        'user_activities': user_activities,
    }
    return render(request, 'main_app/activity_detail.html', context)

@login_required
def add_note(request, user_id):
    form = NoteForm(request.POST)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.user_id = user_id
        new_note.save()
    return redirect('user_activities', user_id=user_id)

class NoteDelete(LoginRequiredMixin,DeleteView):
    model = Note
    success_url = '/activities/'

class NoteUpdate(LoginRequiredMixin,UpdateView):
    model = Note
    fields = ['name', 'content']
    success_url = '/activities/'

class BlogPostList(LoginRequiredMixin,ListView):
    model = BlogPost

class BlogPostCreate(LoginRequiredMixin,CreateView):
    model = BlogPost
    fields = ['title', 'post']

    def form_valid(self, form):
        form.instance.posted_by = self.request.user 
        return super().form_valid(form)

@login_required
def blogpost_detail(request, blogpost_id):
    blogpost = BlogPost.objects.get(id=blogpost_id)
    return render(request, 'blogpost_detail.html', { 'blogpost': blogpost })

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Eco-Acts</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Commissioner&display=swap" rel="stylesheet">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul class="right">
            <!-- changes below -->
            <li><a class="nav-link" href="{% url 'home' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'blog' %}">Blog</a></li>
            <li><a class="nav-link" href="{% url 'index' %}">Activities</a></li>
            <li><a class="nav-link" href="{% url 'user_activities' user.id %}">My Activities</a></li>
            <li><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
                <li><a class="nav-link" href="{% url 'signup' %}">Sign Up</a></li>
                <li><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
      </div>
    </nav>
  </header>
  <main >
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/blog.html
{% extends 'base.html' %}
{% block content %}

<h1>Blog</h1>


{% endblock %}

main_app/templates/blogpost_detail.html
{% extends 'base.html' %}
{% block content %}

<body class="bp-body">
    <h1>{{ blogpost.title }}</h1>
    <p>Posted On: {{ blogpost.post_date }}</p>
    <p>Posted By: {{ blogpost.posted_by }}</p>
    
    <p class="bp-text">{{ blogpost.post }}</p>
    
</body>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<body class="hp-body">
    <div class="hp-container">
        <h1>Welcome to Eco-Acts.</h1>
        <p class="hp-blurb">
            Let us help you begin your new sustainable lifestyle.
        </p>
    </div>
    
</body>


{% endblock %}

main_app/templates/main_app/activity_list.html
{% extends 'base.html' %}
{% block content %}
<body class="activities-body">
<h1 class="act-h1">Activities</h1>
    <div class="activities-div">
        {% for activity in activities %}
            <div class="activities-card">
            <div id="card-row" class="row">
                <div id="card" class="col s12 m6">
                <div class="card blue-grey darken-1" id="activities-card">
                    <div class="card-content">
                    <span id="card-title" class="card-title">{{ activity.name }}</span>
                    <p class="savings">CO2 Savings: {{ activity.savings }} lbs/yr</p>
                    <br>
                    <p>{{ activity.about }}</p>
                    </div>
                    <div id="bottom-card" class="card-action">
                        {% if request.user.username %}
                            {% if activity in user_activities %}
                                <a id="card-btn" class="btn" href="{% url 'unassoc_activity' activity.id request.user.id %}">Delete Activity from My List</a>
                            {% else%}
                                <a id="card-btn" class="btn" href="{% url 'assoc_activity' activity.id request.user.id %}">Add Activity to My List</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

{% endblock %}

main_app/templates/main_app/blogpost_form.html
{% extends 'base.html' %}
{% block content %}

<body class="add-bp">
    <div class="blog-form">
        <h1>Add Blog Post</h1>
        <form action="" method="post">
            <!-- Django requires the following for security purposes -->
            {% csrf_token %}
            <label class="label">Title: 
                <input type="text" name="title">
            </label>
            <label class="label">Post:</label>
                <textarea name="post" id="bp_textarea" cols="30" rows="80"></textarea>
            <input id="card-btn" type="submit" value="Submit!" class="btn">
        </form>
    
    </div>
</body>


{% endblock %}

main_app/templates/main_app/blogpost_list.html
{% extends 'base.html' %}
{% block content %}
<div class="blog-body">
    <h1 class="blog-h1">Share your journey with us...</h1>

    
</div>
<div class="blog-body2">
    <br>
    <a id="add-bp" class="btn" href="{% url 'blogpost_create' %}">Add a Post</a>
    <div class="blog-div"> 
        {% for blogpost in blogpost_list %}
        <div class="blogpost">
            <div class="row">
                <div id="bp-card" class="col s12 m6">
                    <div class="card blue-grey darken-1">
                        <div class="card-content">
                            <span class="card-title">{{ blogpost.title }}</span>
                            <p>Posted: {{ blogpost.post_date }}</p>
                            <p>Posted By:{{ blogpost.posted_by }}</p>
                        </div>
                        <div id="bottom-card" class="card-action">
                            <a id="card-btn" class="btn" href='{% url 'blogpost_detail' blogpost.id %}'>See Post</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/main_app/myactivity_list.html
{% extends 'base.html' %}
{% block content %}

<h1>My Activities</h1>

{% endblock %}

main_app/templates/main_app/note_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Note</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'user_activities' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/note_form.html
{% extends 'base.html' %}
{% block content %}

<h1>Facts Page</h1>

<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/user_activities.html
{% extends 'base.html' %}
{% block content %}
<body class="user-body">
    <h1 class="h1"> {{ user.username }}'s Activities</h1>
    <div class="user-container">
        <div class="user-acts">
            {% for activity in my_activities %}
            <div id="row" class="row">
                <div id="card"  class="col s4">
                <div class="card blue-grey darken-1">
                    <div class="card-content">
                    <span class="card-title">{{ activity.name }}</span>
                    <p>{{ activity.savings }} lbs/yr</p>
                    <p>{{ activity.about }}</p>
                    </div>
                    <div id="bottom-card"  class="card-action">
                        <a id="card-btn" class="btn" href="{% url 'unassoc_activity' activity.id request.user.id %}">Delete Activity</a>
                    </div>
                </div>
                </div>
            </div>   
            {% endfor %}
        </div>
    
        <div class="notes-div">
            <h4>Notes</h4>
            <form class="notes-form" action="{% url 'add_note' user.id %}" method="post">
                {% csrf_token %}
                {{ note_form.as_p }}
                <input id="card-btn" type="submit" class="btn" value="Add Note">
            </form>
            
            {% for note in user.note_set.all %}
            <div class="row">
                <div id="note-card" class="col s12 m6">
                    <div class="card blue-grey darken-1">
                    <div class="card-content">
                        <span class="card-title">{{ note.name }}</span>
                        <p>{{ note.content }}</p>
                    </div>
                    <div id="bottom-card" class="card-action">
                        <a id="card-btn" class="btn" href="{% url 'note_update' note.id %}">Edit</a>
                        <a id="card-btn" class="btn" href="{% url 'delete_note' note.id %}">Delete</a>
                    </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</body>

{% endblock %}

main_app/templates/water_use.html
{% extends 'base.html' %}
{% block content %}

<h1>Water Use Calculator</h1>

{% endblock %}